from django.urls import path
from django.http import HttpResponse    
from ferreteria.views import (alta_bulones,
                            mostrar_bulones,
                            alta_herramientas,
                            alta_pvc,
                            mostrar_herramienta,
                            mostrar_articulo,
                            buscar_bulones,
                            home,
                            FerreteriaBulonesCreateView,
                            FerreteriaBulonesDeleteView,
                            FerreteriaBulonesDetailView,
                            FerreteriaBulonesListView,
                            FerreteriaBulonesUpdateView,
                            FerreteriaPvcCreateView,
                            FerreteriaPvcDeleteView,
                            FerreteriaPvcDetailView,
                            FerreteriaPvcListView,
                            FerreteriaPvcUpdateView,
                            acerca_de)

from accounts.views import ( UserLoginView,
                            UserRegisterView,
                            logout_view,)
app_name="ferreteria"

urlpatterns = [
    path('buloneria/',mostrar_bulones, name='buloneria'),
    path('herramientas/',mostrar_herramienta,name='herramientas'),
    path('accesoriospvc/',mostrar_articulo,name='accesoriospvc'),
    path('alta-bulones/',alta_bulones,name='alta-bulones'),
    path('alta-herramientas/',alta_herramientas,name='alta-herramientas'),
    path('alta-pvc/',alta_pvc,name='alta-pvc'),
    path('buscar-bulones/',buscar_bulones,name='buscar-bulones'),
    path('home/',home,name='home'),
    path("ferreteria/alta-bulones", FerreteriaBulonesCreateView.as_view(), name="buloneria-create"),
    path("ferreteria/buloneria-list",FerreteriaBulonesListView.as_view(), name="buloneria-list"),
    path("bulones/<int:pk>", FerreteriaBulonesDetailView.as_view(), name="buloneria-detail"),
    path("bulones/<int:pk>/editar", FerreteriaBulonesUpdateView.as_view(), name="buloneria-update"),
    path("bulones/<int:pk>/eliminar", FerreteriaBulonesDeleteView.as_view(), name="buloneria-delete"),
    path("ferreteria/alta-pvc", FerreteriaPvcCreateView.as_view(), name="pvc-create"),
    path("pvc-list",FerreteriaPvcListView.as_view(), name="pvc-list"),
    path("articulo/<int:pk>", FerreteriaPvcDetailView.as_view(), name="pvc-detail"),
    path("articulo/<int:pk>/editar", FerreteriaPvcUpdateView.as_view(), name="pvc-update"),
    path("articulo/<int:pk>/eliminar", FerreteriaPvcDeleteView.as_view(), name="pvc-delete"),
    path("", UserLoginView.as_view(), name='login'),
    path('accounts/signup/', UserRegisterView.as_view(), name='signup'),
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),  
    path('ferreteria/acerca-de', acerca_de, name='acerca-de'),
]
