# Generated by Django 5.2 on 2025-04-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FerreteriaBulones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cabeza', models.CharField(max_length=50)),
                ('tamaño_rosca', models.CharField(max_length=10)),
                ('longitud', models.IntegerField()),
            ],
        ),
    ]
