# Generated by Django 5.2 on 2025-04-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0002_ferreteriaherramientas'),
    ]

    operations = [
        migrations.CreateModel(
            name='FerreteriaPvc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesorio', models.CharField(max_length=50)),
                ('rosca', models.CharField(max_length=50)),
            ],
        ),
    ]
